name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e423eb383fc3c30c0edae5a2179a29536399851ab974a92d1568dca1115d8fb2"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
